name: Delete Older Releases

on:
  workflow_dispatch:

jobs:
  delete-older-releases:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      continue-on-error: true
      with:
        keep_latest: 1
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.LEO_TOKEN }}

    - name: Print success message
      run: echo "Older releases and tags deleted successfully!"
